version: "3.8"

services:
  fe:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      API_BASE_URL: ${API_BASE_URL:-http://localhost:4000}
      NITRO_PORT: ${NITRO_PORT:-3000}
      NITRO_HOST: 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - fe_node_modules:/usr/src/app/node_modules
    command: sh -lc "pnpm i && pnpm dev"

volumes:
  fe_node_modules:


