services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bolt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bolt || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  be:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      POSTGRES_URL: ${POSTGRES_URL:-postgres://postgres:postgres@db:5432/bolt}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - be_node_modules:/usr/src/app/node_modules
    command: sh -lc "pnpm i && pnpm db:generate && pnpm db:migrate && pnpm dev"

volumes:
  pgdata:
  be_node_modules:


